### ISSUE TITLE
Can mint nft in inactive project / phase by building a code

### ISSUE THREAD

**Issue by hnnam0906** [ArtZero-io/Contracts#10]
1. MAJESTIC MASK NFT project is inactive project. 
![Inactive project](https://user-images.githubusercontent.com/97796421/218717700-0e2dc8f3-cb90-4bcc-a990-7f12853c37ff.JPG)

2.  Build an ouside code. Before minting, there is no NFT. 
![Before minf - 0 NFT](https://user-images.githubusercontent.com/97796421/218718038-d50dfaef-ac4c-41a9-a5b1-bab8ab8fc30c.png)

3.  After minting, i have 1 NFT
![After mint - 1 nft](https://user-images.githubusercontent.com/97796421/218718204-6801a9ad-1492-42c9-ab0f-5766662124fd.JPG)

I think the similar issue for public_mint and whitelist_mint functions with inactive phases.

**Comment by Albert-Tran** [comment]
Hi @hnnam0906, i fixed the bug is related about phase is deactive
Commit:
https://github.com/ArtZero-io/Contracts/commit/364f1e120bf704c5e17452d15f8961d5f6c1fea5

**Comment by Albert-Tran** [comment]
With issue related about project is deactive, i think we don't need to handle it.
Because if the customer created a new project on our platform, they can give everyone to mint nft as whitelist before going live project. So that is reason, we shouldn't cover it. 
@nad128668 Could u please review it?

**Comment by hnnam0906** [comment]
Fix for inactive phase is  

> Hi @hnnam0906, i fixed the bug is related about phase is deactive Commit: [364f1e1](https://github.com/ArtZero-io/Contracts/commit/364f1e120bf704c5e17452d15f8961d5f6c1fea5)

@Albert-Tran : fixing for inactive phases is ok.

**Comment by hnnam0906** [comment]
> With issue related about project is deactive, i think we don't need to handle it. Because if the customer created a new project on our platform, they can give everyone to mint nft as whitelist before going live project. So that is reason, we shouldn't cover it. @nad128668 Could u please review it?

@Albert-Tran @nad128668 : Need @nad128668 to review.
