### ISSUE TITLE
Should check and use checked_mul/_div/_add/_sub to avoid under/overflow.

### ISSUE THREAD

**Issue by hnnam0906** [ArtZero-io/Contracts#11]
Some codes still use unchecked operations (+ - * /), should use checked funcs instead.
i.e.
1. staking/lib.rs/pub fn claim_reward
```
let reward =
                (self.manager.reward_pool * staked_amount) / (self.manager.total_staked as u128);
```
2. staking/lib.rs/pub fn unstake
```
if request_unstake_time + (self.manager.limit_unstake_time * 60000) > current_time
```
3. marketplace/lib.rs/fn apply_discount
```
return (*input_fee * (10000 - self.manager.staking_discount_rate[index] as u128)) / 10000
```

**Comment by Albert-Tran** [comment]
Hi @hnnam0906 , i fixed this issue 
https://github.com/ArtZero-io/Contracts/commit/456a5f00f1da3ab8a29ccd555997242f4e884728
https://github.com/ArtZero-io/Contracts/commit/9f71369eecdabfd7e55616be34e521a91c33a093

**Comment by hnnam0906** [comment]
@Albert-Tran fn apply_discount should recheck, *input_fee * ... : may overflow if *input_fee is big enough, should change to checked_mul

`return (*input_fee * (10000_u128.checked_sub(self.manager.staking_discount_rate[index] as u128).unwrap())).checked_div(10000).unwrap()`

**Comment by Albert-Tran** [comment]
Hi @hnnam0906 , i changed it 
https://github.com/ArtZero-io/Contracts/blob/feature/openbrush-3.0.0/Azero_Contracts/contracts/marketplace/lib.rs

**Comment by hnnam0906** [comment]
It is ok.
