### ISSUE TITLE
Psp34 standard locked token is still in the locked_tokens mapping after burning.

### ISSUE THREAD

**Issue by hnnam0906** [ArtZero-io/Contracts#12]
Try mint -> lock -> burn psp 34 standard token, the locked token is still in the locked_tokens mapping after burning.

![image](https://user-images.githubusercontent.com/97796421/219014723-3851fd43-fd78-4c9a-b5ba-3ab056e28635.png)

**Comment by Albert-Tran** [comment]
Hi @hnnam0906 , i fixed this issue 
`https://github.com/ArtZero-io/Contracts/commit/94bb5a6275fc42b6e5f4aaf930c61ac4848543d1`

**Comment by hnnam0906** [comment]
@Albert-Tran : should also decrease locked_token_count

**Comment by Albert-Tran** [comment]
Hi @hnnam0906 , i fixed this issue
https://github.com/ArtZero-io/Contracts/commit/3dc4c56f6a9373550a737eb4a125e76000a20291

**Comment by hnnam0906** [comment]
Accept!
