### ISSUE TITLE
Bulk Whitelist

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/Contracts#13]
Add Whitelist functions need to be modified to accept multiple adding.
 account: Vec<AccountId>,
phase_id: u8,
whitelist_amount: Vec<u64>,
whitelist_price: Vec<Balance>

Suggestion to reduce storage cost:
- change u64 to u32
- add function to clear whitelist once project ended

**Comment by Albert-Tran** [comment]
Hi @nad128668 , i created this feature on 
https://github.com/ArtZero-io/Contracts/commit/e45fffd93c6b20d1cd1c19aeb44b46a078b80de5

**Comment by Albert-Tran** [comment]
Hi @nad128668 , i updated the condition when clearing whitelist
https://github.com/ArtZero-io/Contracts/commit/a3acc4ff578b0a86a714b9d6b532df2371413308
