### ISSUE TITLE
Update OB lib

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/Contracts#14]
To latest 3.0.0

**Comment by Albert-Tran** [comment]
Hi @nad128668 , i upgraded our contracts to OP 3.0.0
From
https://github.com/ArtZero-io/Contracts/commit/633580b782ea1bef6465f30b65e2090cf9896eb7 
To
https://github.com/ArtZero-io/Contracts/commit/52c1f75d2423f82b7ddc306d4fc8e63e9c3e115f
