### ISSUE TITLE
Update type for index argument in func get_for_sale_token_id of marketplace

### ISSUE THREAD

**Issue by hnnam0906** [ArtZero-io/Contracts#15]
func get_for_sale_token_id puts index as type u128 to Mapping manager.sale_tokens_ids but in the list func the token_id as type Id is put into this mapping. So if we call get_for_sale_token_id, it will doesn't work but fortunately FE doesn't use this func.

![image](https://user-images.githubusercontent.com/97796421/220096094-6dc2849b-f7e7-487e-95f4-d65bc4e9418a.png)

![image](https://user-images.githubusercontent.com/97796421/220096880-3c3b3876-10ca-44ed-b0ec-ac42befb5a08.png)

**Comment by Albert-Tran** [comment]
Hi @hnnam0906 , could u pls review it https://github.com/727-Ventures/openbrush-contracts/blob/main/lang/src/storage/multi_mapping.rs ? 
I want to use the get_value function to get value at a specific index, now maybe this function doesn't use but i guess we need it in the future.

**Comment by hnnam0906** [comment]
You can change index type in func get_for_sale_token_id from u128 to Id type and in FE you can pass index the same as the list func.

![image](https://user-images.githubusercontent.com/97796421/222327810-8c1b0282-d098-489f-9fe0-8759b3eacd4b.png)

**Comment by hnnam0906** [comment]
Checked on UI contract, type u128 of index is the correct one but the mapping index will start from 0 (not from 1).   

![image](https://user-images.githubusercontent.com/97796421/228130022-1b4f52c3-89d9-40b6-9720-88a6c27fbcbd.png)
