### ISSUE TITLE
Optimize update_collection_owner

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/Contracts#19]
From Dominik:

> The function update_collection_owner does not remove the collection from the owner’s collections, and the removal process can be optimized. The function will insert the collection into the old owner’s collections instead of removing it. Also, this function finds the collection index within the owner’s collections with the time complexity O(n). This can be optimized to O(1) by saving the collection index within this user’s collections. The removal process of the collection from the user’s collection also has a time complexity of O(n). It can be optimized to O(1) by swapping the removed collection for the last collection and removing the last collection.
> 
> Example 1: Alice has 500 collections and wants to remove the 250th collection. We need to iterate over 250 collections to get the index of the removed collection. Ideally, we can save the index of this collection in the collection data, and we can just retrieve the index within Alice’s collections. Note that after implementing this approach, we will also need to update the index of this collection after changing the owner, as two owners will have different collection vectors.
> 
> Example 2: Alice has 500 collections and wants to remove the 250th collection. After removing the 250th collection, the vec needs to be shifted by 250 elements. We can avoid this by swapping the removed element (250th in this case) for the last element (500th in this case) and removing the last element, so there will be no need to shift the vec.

**Comment by hnnam0906** [comment]
I updated at https://github.com/ArtZero-io/Contracts/commit/27fc5ae496b0b975b56c1262c07ba2863fd42bd0
