### ISSUE TITLE
panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by ganesh1997oli** [ArtZero-io/Contracts#7]
I have minted 2 token. But when I try to lock and burn token then `Contract trapped during execution` `panicked at 'called `Option::unwrap()` on a `None` value'` error message display. 

It show issue in this line of [code](https://github.com/ArtZero-io/Contracts/blob/c4a48827769391faea5997ed39c1732209bf8369/Azero_Contracts/impls/psp34_standard/psp34_standard.rs#L59)
`#[modifiers(only_token_owner(self.owner_of(token_id.clone()).unwrap()))]`

I have included screenshot for reference:

![3](https://user-images.githubusercontent.com/42571338/215670132-d46417ac-fd2a-4ada-8d26-ec6570081a58.png)
![1](https://user-images.githubusercontent.com/42571338/215670121-a31440f4-55ad-4aa1-868d-fcd73d68b823.png)
![2](https://user-images.githubusercontent.com/42571338/215670128-e1407556-0b0d-41cd-8143-844fd1ea3f32.png)

**Comment by nad128668** [comment]
Hi, 
Please use U64 instead of U8 in the tokenID input

**Comment by ganesh1997oli** [comment]
> Hi, Please use U64 instead of U8 in the tokenID input

Thanks, for quick response😀.
